### ISSUE TITLE
Make configuration path configurable

### ISSUE THREAD

**Issue by 99linesofcode** [mrsked/mrsk#105]
I would like to be able to use MRSK in other projects and environments (ie. Laravel). While Laravel also stores it's project configuration in the `/config` folder, it uses `.php` files as opposed to `.yml`. Within the context of a Laravel app it would make more sense to me to store the `deploy.yml` file in the project root which is why I would like to be able to configure it.

Think this will be a nice issue for me to dabble with Ruby a bit. There are also quite a few directions we could take this in. I'm currently thinking about writing out a `.mrskrc` on init that will contain this and similar configuration settings in the future. Thoughts?

**Comment by 99linesofcode** [comment]
I'd like to take a stab at this myself. Seems like an easy issue I can use to familiarize myself with the Ruby syntax again 😃

**Comment by 99linesofcode** [comment]
Thanks @kjellberg, missed that option. Let's park the idea of a `.mrskrc` configuration file for now and see whether other usecases arrive that may warrant adding something like that in the future.

**Comment by andresgutgon** [comment]
Hi @99linesofcode you metioned Laravel. Do you have some example repo integrating Kamal with Laravel. Thanks and sorry if this a bit off-topic on this issue

**Comment by 99linesofcode** [comment]
Hi @andresgutgon,

No example repository unfortunately but here's the gist of what I did to deploy a Laravel application succesfully:

1. Create a base image that copies your source code into `/app` and host it on a container registry (for example on Github);
2. Add a healthcheck endpoint (i.e. `/up`). I've used Spatie's [Laravel Health](https://spatie.be/docs/laravel-health/v1/introduction);
3. Define your `deploy.yml` and secrets;
4. Run Kamal. Here is the alias I used when it was still mrsk:

```bash
# mrsk
alias mrsk="docker run -it --rm -v $PWD:/workdir -v $HOME/.gitconfig:/root/.gitconfig -v $SSH_AUTH_SOCK:/ssh-agent -v /var/run/docker.sock:/var/run/docker.sock -e SSH_AUTH_SOCK=/ssh-agent ghcr.io/mrsked/mrsk:latest"
```
Below is an example of the `deploy.yml` I used:

```yml
service: APP_NAME

image: GITHUB_ACCOUNT/
servers:
  - SERVER_IP

registry:
  server: ghcr.io
  username: 99linesofcode
  password:
    - MRSK_REGISTRY_PASSWORD

builder:
  multiarch: false

healthcheck:
  path: /up
  port: 80
```

Good luck!

**Comment by andresgutgon** [comment]
Thanks! I'll try and let you know

**Comment by dorsma** [comment]
Looks like this may relate to #1424
