### ISSUE TITLE
Suggestion: Check for local docker, buildx and Dockerfile

### ISSUE THREAD

**Issue by dvisockas** [mrsked/mrsk#109]
:wave: Hey!

I was exploring `mrsk` and stepped on few rakes that resulted in errors that weren't very clear. Maybe checks for them could be added?

#### No docker installed locally
This could be a simple `which docker` check, but that might not work for other OS.
Not sure how this could be alleviated though, since the build happens locally and multiple OS issue prevails.

#### No buildx installed locally
If `buildx` isn't installed, the `docker buildx` will fail with weird errors that aren't easy to parse. Maybe a command status check for `docker buildx` could be added? Regarding fixing that - ditto as above.

#### Dockerfile not present
Didn't have a `Dockerfile` in my current directory and the `docker buildx build ..... --file Dockerfile . ` failed with rather cryptic message. Simple presence  check for `Dockerfile` would work.

**Comment by dhh** [comment]
Would be happy to see all these checks. Please do investigate!

**Comment by jasonfb** [comment]
I don't have buildx installed
```
% which buildx
buildx not found
```

is this necessary? 

I am stuck over here.... https://github.com/mrsked/mrsk/issues/246
I wonder could this be related (I am on an Apple M1 machine)
