### ISSUE TITLE
Running newly installed docker on remote fails

### ISSUE THREAD

**Issue by kholbekj** [mrsked/mrsk#129]
I tried to spin up a Linode with both Debian 11 and Ubuntu 22.04, and do `mrsk deploy`.

It installs docker, but doesn't find the binary on the subsequent invocation:
```
mrsk deploy
Ensure curl and Docker are installed...
  INFO [c319563f] Running which curl on XXX.XXX.XXX.XXX
  INFO [c319563f] Finished in 0.607 seconds with exit status 0 (successful).
  INFO [a737bb1d] Running which docker on XXX.XXX.XXX.XXX
  INFO [a737bb1d] Finished in 0.216 seconds with exit status 1 (failed).
  INFO [5961af5b] Running apt-get update -y && apt-get install docker.io -y on XXX.XXX.XXX.XXX
  INFO [5961af5b] Finished in 20.454 seconds with exit status 0 (successful).
Log into image registry...
  INFO [ebec287c] Running docker login -u [REDACTED] -p [REDACTED] as kasperholbekjensen@localhost
  Finished all in 21.3 seconds
  ERROR (Errno::ENOENT): No such file or directory - docker
```

**Comment by tbuehlmann** [comment]
@kholbekj: Is it installed locally?

**Comment by kholbekj** [comment]
Ah, no - I have podman aliased to docker in the shell I'm running mrsk from, but I don't have the real docker binary. Is that a requirement?

**Comment by tbuehlmann** [comment]
mrsk is running `docker login`, `docker push` and some other commands, so you need it locally, too.

**Comment by kholbekj** [comment]
I see. if i symlink podman to docker it gets further, but since no registry url is specified (for podman it seems you have to specify the docker.io registry) the login fails. I guess I'l fork and see if I can wire it together :)

**Comment by kholbekj** [comment]
Would close this issue, and open a feature-request in favor of a proper feature request for podman support :)

**Comment by kholbekj** [comment]
Continuing that in #132, thanks!
