### ISSUE TITLE
Feature Request: Podman support

### ISSUE THREAD

**Issue by kholbekj** [mrsked/mrsk#132]
Podman has a number of benefits on the development machine over docker. It would be great if mrsk would leverage either.

I don't think the delta between the current build+push process with docker and podman is huge, the registry would have to always be supplied explicitly rather than rely on dockers defaulting, and the `buildx build` command behaves a little differently. the `--builder` param doesn't exist, and `--push` neither, so breaking into a few steps might be needed.

I'm not really a very proficient docker user, so I'm a bit unsure how to tackle the `--builder` thing, I assume the push issue can be resolved by just pushing in a second command.

**Comment by jeremy** [comment]
Good notes. Duplicates #61.

**Comment by kholbekj** [comment]
Whops, my bad!
