### ISSUE TITLE
Discord - Forum Channel

### ISSUE THREAD

**Issue by acidtib** [mrsked/mrsk#133]
@dhh can you create a forum channel on discord? It will help to answer community questions in an organized way and also serve as documentation for future references.

Currently, I'm answering people's questions in the #general channel and that's getting disorganized.

more info on forum channels https://support.discord.com/hc/en-us/articles/6208479917079-Forum-Channels-FAQ

**Comment by northeastprince** [comment]
You can also answer and/or discuss things in a thread off of a message, that would definitely keep things organized
