### ISSUE TITLE
Allow to prefix commands with sudo

### ISSUE THREAD

**Issue by javierav** [mrsked/mrsk#138]
In a clean installation of an OVH Cloud instance, the default user is ubuntu and not root, so to install dependencies or run Docker commands, they need to use sudo.

**Comment by dhh** [comment]
You can set the ssh/user to deal with this: https://github.com/mrsked/mrsk#using-a-different-ssh-user-than-root

**Comment by javierav** [comment]
@dhh not works!

For example I already set in config

```
ssh:
  user: ubuntu
```

```
$ mrsk deploy

  INFO [77b68fda] Running which curl on <IP>
  INFO [77b68fda] Finished in 1.605 seconds with exit status 0 (successful).
  INFO [2db07bfc] Running which docker on <IP>
  INFO [2db07bfc] Finished in 0.206 seconds with exit status 1 (failed).
  INFO [467a0383] Running apt-get update -y && apt-get install docker.io -y on <IP>
  Finished all in 8.4 seconds
  ERROR (SSHKit::Command::Failed): apt-get update -y && apt-get install docker.io -y exit status: 100
apt-get update -y && apt-get install docker.io -y stdout: Reading package lists...
apt-get update -y && apt-get install docker.io -y stderr: E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
```

But this user != root user, so you need to prefix the `apt` or `docker` commands with sudo to get privileged access.

For using docker without sudo, you could add the user `ubuntu` to the `docker` group to be able to run the command without privileges, but this is not possible for running `apt` which is used in the initial configuration of the server with the `mrsk server bootstrap` command.

Possible solutions are:

1. Support the use of sudo for `apt` and `docker` and use them based on a flag in the configuration.
2. The user has to have `docker` and `curl` installed on the system to prevent `mrsk` from trying to install them automatically and added the user to the `docker` group so that `docker` can be run without using `sudo`. A notice should be added to the `README`.

**Comment by dhh** [comment]
Ah, I see what you mean. I think we're probably better off just documenting this, and then saying that if you want to use MRSK without root, you have to do the bootstraping of installing docker.io and curl yourself. Do add a doc PR for that!
