### ISSUE TITLE
Exit code is 0 even though mrsk deploy failed

### ISSUE THREAD

**Issue by kimmobrunfeldt** [mrsked/mrsk#139]
Using `mrsk deploy` via GH actions caused a few occasions where the deployment action seems to succeed even though the deployment failed.

![Screenshot 2023-03-21 at 20 50 22](https://user-images.githubusercontent.com/1232405/226820244-a88c314d-42ec-4e1d-9784-cad54d196867.png)
![Screenshot 2023-03-21 at 20 50 26](https://user-images.githubusercontent.com/1232405/226820248-d772ef8d-5012-4c14-a9b6-aa5f045f6437.png)

**Comment by szluyufeng** [comment]
I have encountered the same problem. Have you managed to solve it?
I am stuck at this point.

**Comment by dhh** [comment]
Solved by #166.
