### ISSUE TITLE
Updating traefik options results to exit code 125 

### ISSUE THREAD

**Issue by kimmobrunfeldt** [mrsked/mrsk#140]
When deploying with updated traefik options, I got this error during `mrsk deploy`

```
Ensure Traefik is running...
  INFO [3253ca90] Running docker run --name traefik --detach --restart unless-stopped --log-opt max-size=10m --publish 80:80 --volume /var/run/docker.sock:/var/run/docker.sock traefik --providers.docker --log.level=DEBUG --entryPoints.web.forwardedHeaders.insecure on 162.55.41.175
  INFO [3253ca90] Finished in 0.382 seconds with exit status 125 (failed).
```

First deployment done with: no traefik options in yml config. Second deployment (when error occured) was done with these updated options:

```yml
traefik:
  args:
    entryPoints.web.address: ':80'
    entryPoints.web.forwardedHeaders.insecure: true
```

**Comment by kimmobrunfeldt** [comment]
Workaround for this was to SSH into the machine and run `docker stop traefik && docker rm traefik` before deployment

**Comment by calmyournerves** [comment]
Out of curiosity: Does it work with `entryPoints.web.forwardedHeaders.insecure: 'true'`?

**Comment by kjellberg** [comment]
> Workaround for this was to SSH into the machine and run `docker stop traefik && docker rm traefik` before deployment

Try with

`mrsk traefik reboot`

https://github.com/mrsked/mrsk/blob/83dc82661b8a02dd1fbb0ee91261104cee127862/lib/mrsk/cli/traefik.rb#L7

**Comment by kimmobrunfeldt** [comment]
@calmyournerves I got those options working when using latest master. I'm running CloudFlare -> Treafik -> tileserver-gl-light, which requires x-forwarded headers from CF to be passed through.

**Comment by kimmobrunfeldt** [comment]
@kjellberg thanks for the tip! 

I was first thinking: what if mrsk automatically updated traefik (i.e. did a reboot and would start it with new options) when required, but it could be quite weird default considering the goal is zero downtime deployments.  Not sure how these updates were intended to be dealt with. Anyways wanted to report!

**Comment by osbre** [comment]
I'm having the same issue by using custom Traefik labels in the `servers.web.labels` section.

**Comment by dhh** [comment]
Is this still an issue with 0.10+?

**Comment by tannakartikey** [comment]
> Is this still an issue with 0.10+?

@dhh, I did not face the error on the `main` branch.
