### ISSUE TITLE
Prune based on number rather than time

### ISSUE THREAD

**Issue by dhh** [mrsked/mrsk#15]
We should be pruning old images and containers on the basis of numbers rather than time. You might well deploy a gazillion times within 30 days. All we need is, say, 5-10 old revisions available for quick rollback.

**Comment by azolf** [comment]
I'm going to open a PR for this

**Comment by azolf** [comment]
@dhh Take a look at this [PR](https://github.com/rails/mrsk/pull/28).

**Comment by dhh** [comment]
Just lowered image lifetime to 7 days instead. Let's cut with Docker's grain.
