### ISSUE TITLE
Mrsk does not show descriptive error message if it can not SSH into the server successfully

### ISSUE THREAD

**Issue by tannakartikey** [mrsked/mrsk#172]
If Mrsk can not connect to the server through SSH, it throws out the error message "Deploy lock found" which is incorrect and confusing.

### Steps to reproduce
I put the following in my `deploy.yml` file:

```
servers:
  web:
    - 127.0.0.1
```

I don't have SSH set up on localhost and hence the connection should fail. Instead, I got the following error message:

```
$ mrsk deploy
ERROR (Mrsk::Cli::Base::LockError): Deploy lock found
```

The `audit` command threw a more relevant error though:
```
$ mrsk audit
ERROR (Errno::ECONNREFUSED): Connection refused - connect(2) for 127.0.0.1:22
```

**Comment by jasonfb** [comment]
yes I saw this too and agree it is poor error messaging. especially for a new product, developer friction is very important to focus on so I agree this should get fixed.

you can also see the real error if you do
`mrsk lock release`

**Comment by huksley** [comment]
Stubled upon the same problem, `mrsk build deliver` gives this error, but `mrsk lock status` shows that it cannot connect to remote host.
