### ISSUE TITLE
mrsk newbie ， ssh host login failed

### ISSUE THREAD

**Issue by zmoon460** [mrsked/mrsk#173]
OS: 
[root@zhaodev ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

[root@zhaodev appdemo]# mrsk lock  status
  INFO [6a2bd968] Running /usr/bin/env stat mrsk_lock > /dev/null && cat mrsk_lock/details | base64 -d on 192.168.0.18
  ERROR (Net::SSH::AuthenticationFailed): Authentication failed for user root@192.168.0.18

[root@zhaodev appdemo]# ssh 192.168.0.18
Last login: Sun Apr  2 16:19:33 2023 from 192.168.0.18

I need upgrade openssh-server  version  or   update mrsk project netssh  ?

**Comment by zmoon460** [comment]
Before using mrsk, I had upgraded a non-RedHat distribution of OpenSSH，maybe I should revert to the original version?

[root@zhaodev appdemo]# ssh -V
OpenSSH_9.0p1, OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by bohdan-shulha** [comment]
I use MacOS and have the similar issue. 

I had to modify the proposed command alias. This one works perfectly fine:

```
alias mrsk="docker run -it --rm -v '${PWD}:/workdir' -v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/mrsked/mrsk:latest"
```

https://github.com/docker/for-mac/issues/410

Not sure if it will work for you, as use use CentOS instead.

**Comment by jasonfb** [comment]
@zmoon460 -- I just submitted a pull request to the docs to clarify this:
https://github.com/mrsked/mrsk/pull/177

you must be sure to SSH into the instance successfully first. when you do, you will be adding your key to `~/.ssh/known_hosts` which is prerequisite to `mrsk deploy`

**Comment by zmoon460** [comment]
I have SSH key trust and do not need a password

May it be the same as this question?
 https://github.com/mrsked/mrsk/issues/180

**Comment by kozubdanil** [comment]
Is there a way to specify ssh key to connect with? I am connected to server via ssh, but mrsk still returns Net::SSH::AuthenticationFailed

**Comment by dhh** [comment]
Closed as dup of https://github.com/mrsked/mrsk/issues/180

**Comment by milushov** [comment]
In case you have an issue with the alias working with more than one project: https://github.com/mrsked/mrsk/discussions/383#discussioncomment-6599876
