### ISSUE TITLE
getting `Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)` on `mrsk deploy`

### ISSUE THREAD

**Issue by jasonfb** [mrsked/mrsk#178]
Using Amazon EC2 instance for **Ubuntu** with a private key (`.pem` file) 

I am able to successfully get mrsk to connect to the instance but when I deploy it tells me this: 

```
% mrsk deploy      
Acquiring the deploy lock
  INFO [5082c2e4] Running /usr/bin/env mkdir mrsk_lock && echo "TG9ja2VkIGJ5OiBKYXNvbiBGbGVldHdvb2QtQm9sZHQgYXQgMjAyMy0wNC0w
MyAxNjo1MjozOSBVVEMKVmVyc2lvbjogM2QwNWFiNWM2NDZkOTg0M2FkZDVj
MmFkZGIwMTY4ZTRiNjkzZWI4MgpNZXNzYWdlOiBBdXRvbWF0aWMgZGVwbG95
IGxvY2s=
" > mrsk_lock/details on 52.207.213.41
  INFO [5082c2e4] Finished in 0.935 seconds with exit status 0 (successful).
Ensure curl and Docker are installed...
  INFO [64a7151b] Running which curl on 52.207.213.41
  INFO [64a7151b] Finished in 0.075 seconds with exit status 0 (successful).
  INFO [ef5579f6] Running which docker on 52.207.213.41
  INFO [ef5579f6] Finished in 0.079 seconds with exit status 1 (failed).
  INFO [27e4ee6d] Running apt-get update -y && apt-get install docker.io -y on 52.207.213.41
  Finished all in 0.3 seconds
Releasing the deploy lock
  INFO [630794ee] Running /usr/bin/env rm mrsk_lock/details && rm -r mrsk_lock on 52.207.213.41
  INFO [630794ee] Finished in 0.082 seconds with exit status 0 (successful).
  ERROR (SSHKit::Command::Failed): apt-get update -y && apt-get install docker.io -y exit status: 100
apt-get update -y && apt-get install docker.io -y stdout: Reading package lists...
apt-get update -y && apt-get install docker.io -y stderr: E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

```

**Comment by jasonfb** [comment]
@heartcombo says via SLACK
>> So, I think that the issue is that the script isn't adding sudo in there because it's expecting the user to be a root user

**Comment by wenlingang** [comment]
It seems that only root users are currently supported

**Comment by intrip** [comment]
The issue is that if you don't want to log in as root you need to pre-install `curl` and `docker` on the hosts.
The error is triggered by this check:

https://github.com/mrsked/mrsk/blob/main/lib/mrsk/cli/server.rb#L6-L13

**Comment by jasonfb** [comment]
@intrip -- as far as i know, there is no way to ssh as root into the EC2 instances(?)

so you're saying I can ssh in using the admin user, sudo, then pre-install curl and docker?

just want to make sure I understand correctly.

**Comment by intrip** [comment]
> so you're saying I can ssh in using the admin user, sudo, then pre-install curl and docker?

Yes that would work

**Comment by jasonfb** [comment]
I was able to get past the above blocker by sshing into the instance and running `sudo su`

then I ran these install commands myself using

`apt-get update -y && apt-get install docker.io -y`
which works successfully after I become the root user manually.

But now `mrsk deploy` is stuck here:

```
  ERROR (SSHKit::Command::Failed): which docker || (apt-get update -y && apt-get install docker.io -y) exit status: 142
which docker || (apt-get update -y && apt-get install docker.io -y) stdout: Please login as the user "ubuntu" rather than the user "root".
which docker || (apt-get update -y && apt-get install docker.io -y) stderr: Nothing written

the thing that doesn't make sense is that `which docker` should find the docker, when i ssh in directly, it does this:

ubuntu@ip-172-31-92-7:~$ which docker
/usr/bin/docker
ubuntu@ip-172-31-92-7:~$ which docker || (apt-get update -y && apt-get install docker.io -y)
/usr/bin/docker
ubuntu@ip-172-31-92-7:~$ which docker || (apt-get update -y && apt-get install docker.io -y) 
/usr/bin/docker


So I'm not sure why `mrsk deploy` is failing here

the full output I see is

```
% mrsk deploy             
  INFO [97f3ea00] Running which docker || (apt-get update -y && apt-get install docker.io -y) on 18.233.99.206
  Finished all in 11.1 seconds
  ERROR (SSHKit::Command::Failed): which docker || (apt-get update -y && apt-get install docker.io -y) exit status: 142
which docker || (apt-get update -y && apt-get install docker.io -y) stdout: Please login as the user "ubuntu" rather than the user "root".
which docker || (apt-get update -y && apt-get install docker.io -y) stderr: Nothing written

```

**Comment by jasonfb** [comment]
my `config/deploy.yml` has this:
```
# Use a different ssh user than root
ssh:
  user: ubuntu
```

**Comment by ilyasbest1234** [comment]
&gt; It seems that only root users are currently supported.
you don't know and you're talking
