### ISSUE TITLE
Configure logging driver to limit output

### ISSUE THREAD

**Issue by dhh** [mrsked/mrsk#18]
Start containers with some logging options so that we don't clog up the hosts by default: https://www.freecodecamp.org/news/how-to-setup-log-rotation-for-a-docker-container-a508093912b2/

**Comment by azolf** [comment]
Here is the [PR](https://github.com/rails/mrsk/pull/27) to support logging.

**Comment by dhh** [comment]
Docker actually has a log-driver that does all this stuff for us. Switched to it with https://github.com/mrsked/mrsk/commit/a80289d0460f6757a752186bfae42de10b19d6ec.
