### ISSUE TITLE
ERROR (Mrsk::Cli::Base::LockError): Deploy lock found

### ISSUE THREAD

**Issue by talhashoaib** [mrsked/mrsk#185]
Doing a fresh deploy and getting 
`ERROR (Mrsk::Cli::Base::LockError): Deploy lock found`

**Comment by tannakartikey** [comment]
@talhashoaib can you verify that you can log into the server via SSH?

If not, then this can be the issue: https://github.com/mrsked/mrsk/issues/172

**Comment by talhashoaib** [comment]
@tannakartikey No, the issue was related to having login to SSH without password.
