### ISSUE TITLE
(question) remote builder: permission denied ?

### ISSUE THREAD

**Issue by charnould** [mrsked/mrsk#192]
In order to speed up MRSK deploy (using an Apple M1 and deploying on a AMD Hetzner VM) I use the following minimal `mrsk.yaml`.

```
service: xyz

image: charnould/xyz

servers:
  - 99.999.999.99

registry:
  username: charnould
  password:
    - MRSK_REGISTRY_PASSWORD

builder:
  remote:
    arch: amd64
    host: ssh://root@99.999.999.99
```

But when typing `mrsk deploy`, I've got a new error I hadn't before.

```
Build and push app image...
  INFO [138e6b47] Running docker buildx build --push --platform linux/amd64 --builder mrsk-malro-native-remote -t charnould/malro:71f333b1f16f7aef5c8395c9b4e33eec1a1125a2 -t charnould/malro:latest --label service="malro" --file Dockerfile . as charnould@localhost
 DEBUG [138e6b47] Command: docker buildx build --push --platform linux/amd64 --builder mrsk-malro-native-remote -t charnould/malro:71f333b1f16f7aef5c8395c9b4e33eec1a1125a2 -t charnould/malro:latest --label service="malro" --file Dockerfile .
 💥💥 DEBUG [138e6b47]       ERROR: no builder "mrsk-malro-native-remote" found
 ERROR Missing compatible builder, so creating a new one first
  INFO [292bddc5] Running docker context create mrsk-malro-native-remote-amd64 --description 'mrsk-malro-native-remote amd64 native host' --docker 'host=ssh://root@99.999.999.99' ; docker buildx create --name mrsk-malro-native-remote mrsk-malro-native-remote-amd64 --platform linux/amd64 as charnould@localhost
 💥💥 ERROR Couldn't create remote builder: Permission denied, please try again.
```

Trying to debug, I've typed directly into my VM console the command MRSK tried to use:

`docker context create mrsk-malro-native-remote-amd64 --description 'mrsk-malro-native-remote amd64 native host' --docker 'host=ssh://root@99.999.999.99'`...

...then `docker buildx create --name mrsk-malro-native-remote mrsk-malro-native-remote-amd64 --platform linux/amd64`, but got an error for this one: `unknown flag: --name`

Do you know why my deploy fails? (my SSH key with passphrase works fine)
Thanks.

**Comment by dhh** [comment]
Looks like a permission issue with Docker on Hetzner VMs. See http://stackoverflow.com/questions/48957195/ddg#48957722. Feel free to open a PR explaining how to sidestep this once you've found a solution.

**Comment by jeremy** [comment]
```bash
docker context create mrsk-malro-native-remote-amd64 --description 'mrsk-malro-native-remote amd64 native host' --docker 'host=ssh://root@99.999.999.99'
docker buildx create --name mrsk-malro-native-remote mrsk-malro-native-remote-amd64 --platform linux/amd64
```

1. Note that these commands are run _locally_, not on your VM.
2. The `context create` command is what's failing: "ERROR Couldn't create remote builder: Permission denied, please try again."

This is due to not being able to SSH to `root@99.999.999.99` from your local shell. Get that working first, then focus on getting the context create to work (`docker context create mrsk-malro-native-remote-amd64 --description 'mrsk-malro-native-remote amd64 native host' --docker 'host=ssh://root@99.999.999.99'`), and you should be good to go.

**Comment by shafy** [comment]
Sorry for commenting on a closed issue, but I didn't find a solution to this and have the same problem.

> This is due to not being able to SSH to root@99.999.999.99 from your local shell.

In my case, running `shh root@<ip_address>` works just fine, but I still get the same error message as OP. What am I missing?
