### ISSUE TITLE
Mysql2::Error::ConnectionError /tmp/mysql.sock

### ISSUE THREAD

**Issue by HazzaAlkaabi** [mrsked/mrsk#199]
Hi all,

I was following @dhh video on MRSK and reached the point where we type "mrsk setup" which I attempted to execute but i got the following:

ERROR bin/rails aborted!
ActiveRecord::ConnectionNotEstablished: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

Caused by:
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

Tasks: TOP => db:prepare
(See full trace by running task with --trace)
  INFO [4e13e59e] Running docker container ls --all --filter name=healthcheck-tahadi --quiet | xargs docker stop on {IP}
  INFO [4e13e59e] Finished in 0.936 seconds with exit status 0 (successful).
  INFO [e9350fa5] Running docker container ls --all --filter name=healthcheck-tahadi --quiet | xargs docker container rm on 5.161.200.66
  INFO [e9350fa5] Finished in 1.449 seconds with exit status 0 (successful).
  Finished all in 566.1 seconds
  Finished all in 578.1 seconds
  ERROR (SSHKit::Command::Failed): Health check against /up failed to return 200 OK!

**Comment by dhh** [comment]
You need to point your production mysql to the proper host in config/database.yml. Either way, please direct usage questions to the Discord server.
