### ISSUE TITLE
Publishing multiple intermediary instances to container registry

### ISSUE THREAD

**Issue by arvindsivakumar** [mrsked/mrsk#234]
I wanted to say thanks for publishing such an awesome tool! It has really simplified my deployment process & and I am really enjoying the DX gains 😄. 

I'm running into some issues publishing to my container registry (hosted on Digital Ocean). When I run `mrsk deploy` it seems that several duplicate (or potentially intermediary) images are getting published along with the final tagged image. 

Here's a an example of what that the registry will look like after running `mrsk deploy`: 

<img width="1337" alt="Screenshot 2023-04-19 at 6 17 27 PM" src="https://user-images.githubusercontent.com/2498230/233219564-b2272226-0b8f-4841-96b4-2464bd5a0be2.png">

Not sure if others have run into this issue, and would appreciate any guidance or workarounds!

### Additional Details on Reproduction

1. `mrsk` was run locally on an M2 Macbook
2.  Issue is present on `mrsk` version `0.11.0`

**Comment by dhh** [comment]
The default is multi-arch. So when you build on M2, each image will come in both amd64 and arm64 versions. This is by design, so the build will run on both the M2 and a remote Intel chip 👍
