### ISSUE TITLE
Deploy lock is not released when mrsk can't find env variable

### ISSUE THREAD

**Issue by bohdan-shulha** [mrsked/mrsk#236]
Hi team,

Yet another attempt to approach mrsk. :)

I have discovered, probably, a bug.

So, I have created a simple config for testing purposes:

```
$ cat deploy.yml

service: front-office
image: e-sportstats/front-office
servers:
  - 165.22.1.24
registry:
  username:
    - MRSK_REGISTRY_PASSWORD
  password:
    - MRSK_REGISTRY_PASSWORD

```

Then I have tried to run a deploy for the first time.

```
└──── $ mrsk deploy -c scripts/mrsk/deploy.yml
Acquiring the deploy lock
  INFO [542e6142] Running /usr/bin/env mkdir mrsk_lock && echo "TG9ja2VkIGJ5OiBCb2hkYW4gU2h1bGhhIGF0IDIwMjMtMDQtMjAgMTE6MTM6
NDkgVVRDClZlcnNpb246IDgyYmUxNTZlMDY3MGQ1N2Q5M2M4ZWNlY2ZkNGYz
YWYxMDUzYWQ0YjMKTWVzc2FnZTogQXV0b21hdGljIGRlcGxveSBsb2Nr
" > mrsk_lock/details on 165.22.1.24
  INFO [542e6142] Finished in 1.374 seconds with exit status 0 (successful).
Ensure curl and Docker are installed...
  INFO [2c9395b2] Running which curl on 165.22.1.24
  INFO [2c9395b2] Finished in 0.244 seconds with exit status 0 (successful).
  INFO [7a79f5cb] Running which docker on 165.22.1.24
  INFO [7a79f5cb] Finished in 0.242 seconds with exit status 1 (failed).
  INFO [ced2bd92] Running apt-get update -y && apt-get install docker.io -y on 165.22.1.24
  INFO [ced2bd92] Finished in 19.327 seconds with exit status 0 (successful).
Log into image registry...
  Finished all in 19.8 seconds
  Deploy lock was not released
  ERROR (KeyError): key not found: "MRSK_REGISTRY_PASSWORD"
```

Unfortunately, config was mostly copy-pasted from docs and MRSK_REGISTRY_PASSWORD variable was not defined (I had a different name). You may see that `deploy lock was not released`.

I'm quite unsure that this is the correct behavior - no critical changes were introduced to host.

**Comment by dhh** [comment]
Cc @djmb

**Comment by djmb** [comment]
@bohdan-shulha - I think https://github.com/mrsked/mrsk/pull/211 should have fixed this, though it's not in a released version yet. Could you see if your issue is resolved in the main branch?

@jasonfb - hopefully that PR will also solve most of your locking annoyances as well, but if not, please do raise an issue.
