### ISSUE TITLE
Missing encryption key to decrypt file with. Ask your team for your master key and write it to /rails/config/master.key or put it in the ENV['RAILS_MASTER_KEY']

### ISSUE THREAD

**Issue by jmarsh24** [mrsked/mrsk#266]
### Discussed in https://github.com/mrsked/mrsk/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **jasonfb** May  2, 2023</sup>
**Testing using MRSK 0.11.0**

Please bear with me as I am working through numerous MRSK setup issues and I am new to MRSK and relatively new to Docker.

Initially started building this app using the default `config/deploy.yml` file, making small tweeks and re-testing each time as I worked through various issues.

Somewhere along the way, I uncommented this code in the deploy.yml file:

(1)
```
env:
  secret:
    - RAILS_MASTER_KEY
```

Note that I just uncommented the code, leaving the characters `RAILS_MASTER_KEY` as just a string. It is not clear to me reading the instructions and default of the file whether it should have been replaced by my _real master key_ (or not?).

I was confused by the comment in the default file that reads: "(secrets come from .env)" which made me think that the string  `RAILS_MASTER_KEY` would get replaced by the secret in the `.env` file.

Somewhere along the way, someone on SLACK suggested this as a way to bring your Ruby version, bundler version, and secret key into the MRSK setup:

(2)
```
builder:
  args:
    RUBY_VERSION: "<%= Pathname.pwd.join('.ruby-version').read.strip.delete_prefix('ruby-') %>"
    BUNDLER_VERSION: "<%= Bundler::LockfileParser.new(Pathname.pwd.join('Gemfile.lock').read).bundler_version %>"
    RAILS_MASTER_KEY: "<%= ENV['RAILS_MASTER_KEY'] %>"
```
(Notice that these are builder args, not env secret)

Should I also do this same syntax for **env** **secret** configured in `config/deploy.yml`?

If I do this:
(3)
```
env:
  secret:
    - "<%= ENV['RAILS_MASTER_KEY'] %>"
```

then I can no longer do anything with MRSK  at all --it's like I'm borked now --- `mrsk lock release` and `mrsk deploy` both now tell me: 

  ERROR (KeyError): key not found: "f0e5e49fXXXXXXXXXXXXXXXXXXXXXX"

(rest of key has been obscured for privacy but I confirmed it matches my real secret key. )

If I use the original syntax (#1), then the lock mechanism works as expected to release the lock, but when I try to deploy, I get:

```
 > [linux/arm64 build 10/10] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile:
#0 0.977 Missing encryption key to decrypt file with. Ask your team for your master key and write it to /rails/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
------
Dockerfile:53
--------------------
  51 |     
  52 |     # Precompiling assets for production without requiring secret RAILS_MASTER_KEY
  53 | >>> RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
  54 |     
  55 |     
```

Note that in production.rb this line has been UNCOMMENTED: 
```
  config.require_master_key = true
```

as well, my app contains `config/master.key` (but it is not being copied into the container by Dockerfile), and my app also has the RAILS_MASTER_KEY set as an `.env` variable.  

if I locally run `RAILS_ENV=production rails s`, I get these result:

```
3.1.2 :005 > Rails.application.credentials.key_file_contents
 => nil 
3.1.2 :006 > Rails.application.credentials.env_key
 => "RAILS_MASTER_KEY" 
3.1.2 :007 > Rails.application.credentials.key_file_contents
 => nil 
3.1.2 :008 > ENV['RAILS_MASTER_KEY']
 => nil 
```

if I instead run `RAILS_ENV=development rails s`, I get this:

```
3.1.2 :002 > Rails.application.credentials.env_key
 => "RAILS_MASTER_KEY" 
3.1.2 :003 > Rails.application.credentials.key_file_contents
 => nil 
3.1.2 :001 > ENV['RAILS_MASTER_KEY']
 => "f0e5e49fXXXXXXXXXXXXXXXXXXXXXXXXX" 
```

The Dockerfile is the same Dockerfile found on https://www.driftingruby.com/episodes/deploying-with-mrsk and the line that it fails on is:

```
# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
```

</div>

**Comment by jmarsh24** [comment]
@PabloC Could you be more specific?

(1) outlines this as the initial try. Which from what I can read is the same thing you are recommending.

```env:
  secret:
    - RAILS_MASTER_KEY```

**Comment by dhh** [comment]
Please keep the usage discussion in https://github.com/mrsked/mrsk/discussions/263. There's no bug report here yet.

**Comment by jasonfb** [comment]
see https://stackoverflow.com/questions/76157925/rails-7-validate-secret-key-base-missing-secret-key-base-for-production-e/76190212 for answer — my problem was I was trying to use `SECRET_KEY_BASE_DUMMY=1` in Rails 7.0
