### ISSUE TITLE
Doesn't install Docker on server (Hetzner)

### ISSUE THREAD

**Issue by shafy** [mrsked/mrsk#301]
I've created a new Hetzner VM (Ubuntu 22.04, AMD) and would expect MRSK to install Docker on the remote machine. However, `mrsk deploy` fails with:

```zsh
Acquiring the deploy lock
  INFO [4aeec3cb] Running /usr/bin/env mkdir mrsk_lock && echo "TG9ja2VkIGJ5OiBDYW4gT2xjZXIgYXQgMjAyMy0wNS0xOFQxMDoyMTo0OFoK
VmVyc2lvbjogNjkzMGQyOGMzMzNlNzY1OTg4ZjM0ZDFjYzViODcxZTY2ZTRj
ZjZlMgpNZXNzYWdlOiBBdXRvbWF0aWMgZGVwbG95IGxvY2s=
" > mrsk_lock/details on 195.201.6.85
Enter passphrase for /Users/canolcer/.ssh/id_ed25519:
  INFO [4aeec3cb] Finished in 5.974 seconds with exit status 0 (successful).
Log into image registry...
  INFO [b930d534] Running docker login ghcr.io -u [REDACTED] -p [REDACTED] as canolcer@localhost
  INFO [b930d534] Finished in 0.914 seconds with exit status 0 (successful).
  INFO [11b61771] Running docker login ghcr.io -u [REDACTED] -p [REDACTED] on 195.201.6.85
  Finished all in 1.0 seconds
Releasing the deploy lock
  INFO [405eff61] Running /usr/bin/env rm mrsk_lock/details && rm -r mrsk_lock on 195.201.6.85
  INFO [405eff61] Finished in 0.110 seconds with exit status 0 (successful).
  ERROR (SSHKit::Command::Failed): docker exit status: 127
docker stdout: Nothing written
docker stderr: bash: line 1: docker: command not found
```

My SSH key does have root access. After installing Docker manually this problem goes away.

According to the MRSK source, not having Docker installed and failing to install Docker [should show an error message](https://github.com/mrsked/mrsk/blob/a7d869ad40b2a39286139f5c110d679602ba160d/lib/mrsk/cli/server.rb#L7). However, this doesn't happen in my case.

Any ideas?

**Comment by shafy** [comment]
This solves this issue, thanks! However, this is not made clear in the docs. In fact, there it is implied that `mrsk deploy` installs Docker. I'll make a PR.

**Comment by dhh** [comment]
Should add a note to docs about it.
