### ISSUE TITLE
Traefik log level forced to DEBUG

### ISSUE THREAD

**Issue by igor-alexandrov** [mrsked/mrsk#319]
Currently, Traefik log level is forced to DEBUG. 

Based on this code https://github.com/mrsked/mrsk/blob/de2de19434d0a1682c1068a98a2bc3e787063531/lib/mrsk/commands/traefik.rb#LL20C8-L20C23, the value that you provide in `deploy.yml` will always be replaced with `--log.level=DEBUG`.

Is this an issue or an intentional decision?

**Comment by dhh** [comment]
Would be happy to take a PR that'll let you overwrite that value.

**Comment by igor-alexandrov** [comment]
Will do!
