### ISSUE TITLE
Cached multistage docker builds for faster builds

### ISSUE THREAD

**Issue by saborrie** [mrsked/mrsk#329]
In stacks such as C#.NET that need to compile the source code, Dockerfiles are often multistage, first building using an SDK base image, then copying the built output into a smaller base image with only a runtime.

A full typical C#.NET Dockerfile will look like this:

```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MyProject/MyProject.csproj", "MyProject/"]
RUN dotnet restore "MyProject/MyProject.csproj"
COPY . .
WORKDIR "/src/MyProject"
RUN dotnet build "MyProject.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyProject.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyProject.dll"]
```

But for the sake of understanding this issue, this can be simplified to this pseudo Dockerfile:

```Dockerfile
FROM sdk-image AS build
WORKDIR /src
COPY ["mycode/", "mycode/"]
RUN build --output /app/build

FROM runtime-image as final
WORKDIR /app
COPY --from=build /app/build
ENTRYPOINT ["runtime", "mycode"]
```

These kinds of multistage Dockerfiles are very useful in ensuring that final image is very small - although the SDK is required during the build stage, we deploy an image with only a runtime and our compiled code to our app servers.

However, since our published images are so small, they are useless for caching our build steps - we're specifically removing all the build layers by doing the multistage.

The native docker solution is to use a "Cache Storage Backend": https://docs.docker.com/build/cache/backends/

I have also previously successfully sped up my builds for lots of .NET projects using a script similar to this:

```shell
export ${IMAGE}=myimage
export BUILD_CACHE=${IMAGE}:latest-build
export LATEST=${IMAGE}:latest
export NEW_TAG=${IMAGE}:${GIT_SHA}

docker pull $BUILD_CACHE
docker pull $LATEST

docker build --target build --cache-from $BUILD_CACHE --tag $BUILD_CACHE .
docker build --cache-from $BUILD_CACHE --cache-from $LATEST --tag $LATEST--tag $NEW_TAG .

docker push $BUILD_CACHE
docker push $LATEST
docker push $NEW_TAG
```

I don't know how the internals of MRSK works, so I'm not sure whether either solution can be used, but it would be good to think about supporting some way of doing cached multistage builds - either directly or through user-specified customisations - or at least write docs that explain that it won't be cached.

---

An alternative approach could be something like [the Bazel OCI rules](https://github.com/bazel-contrib/rules_oci) which *don't even require a docker host* to build docker images.

**Comment by brunoprietog** [comment]
Rails Dockerfiles also uses them, it should not be a problem

**Comment by igor-alexandrov** [comment]
I already experimented with multistage cached builds with MRSK. Results are here: https://twitter.com/igor_alexandrov/status/1669636689311023104
