### ISSUE TITLE
echo stderr: zsh:1: no matches found: [YYYY-MM-DDTHH:MM:SSZ]

### ISSUE THREAD

**Issue by fernandomenolli** [mrsked/mrsk#330]
Hello,

I'm facing an error when I try to deploy an app when using mrsk >= v12.1, error below:

```
 DEBUG [c5822ec9] 	#44 DONE 99.5s
  INFO [c5822ec9] Finished in 150.434 seconds with exit status 0 (successful).
  Finished all in 155.1 seconds
Releasing the deploy lock...
  Finished all in 156.2 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 10.20.150.152: echo exit status: 1
echo stdout: Nothing written
echo stderr: zsh:1: no matches found: [2023-06-09T13:28:32Z]
```
When I use mrsk version 0.11, the error doesn't occur, any ideas? I noticed that logs have datetime written in different way in version 12.1 forward, most recent versions use ISO 8601 date format, is this related?

Thank you.

**Comment by guilhermeyo** [comment]
I had the same problem when I upgraded from 0.10.1 to 13.0.2, and I rollback to 0.10.1, which works. I will try again. If I find a solution, I will answer here.

**Comment by fernandomenolli** [comment]
Hello,
I found out what was going on, the problem was in my "Oh my zsh", I tried to deploy using mrsk on a VM without Oh My Zsh and everything was fine, when I installed "Oh my zsh" again, the problem appeared again.

Thank you.

**Comment by matthee** [comment]
I'm also experiencing this error. I've found this error relates to an unquoted call to `echo` when logging to the `mrsk-[app]-audit.log` file.

I've narrowed it down to the following command being run: 

```sh
/usr/bin/env echo [2023-06-20T23:58:59Z] [user] Pulled image with version 341f05ef2cb9560e262b9c4b4ac44fd74c24e582_uncommitted_1d8b81b3a7c8b973 >> mrsk-[app]-audit.log on [host]
```

IMHO the command arguments need escaping, like so:

```sh
/usr/bin/env echo "[2023-06-20T23:58:59Z] [user] Pulled image with version 341f05ef2cb9560e262b9c4b4ac44fd74c24e582_uncommitted_1d8b81b3a7c8b973" >> mrsk-[app]-audit.log on [host]
```

When reading through the code base, I've found [this line](https://github.com/mrsked/mrsk/blob/main/lib/mrsk/cli/build.rb#L42), which is probably responsible for this bug. However I think we could this issue by quoting the arguments globally in the [Auditor](https://github.com/mrsked/mrsk/blob/main/lib/mrsk/commands/auditor.rb#L12).

**Comment by jwthomp** [comment]
If you are running into this with `zsh` and waiting for a fix, you can create a `~/.zshenv` and add the line:
```
setopt +o nomatch
```
to it. This will disable the matching it is trying to do and behave like bash.

**Comment by 99linesofcode** [comment]
Just got bitten by this as well. Seems very trivial to fix. Could we reopen? The fix proposed is simply to uninstall oh-my-zsh but that's not a solution to the issue. Could someone that is familiar with the codebase take a stab at this?

**Comment by mklasen** [comment]
@jwthomp's suggestion above fixed the issue for me as well :)

**Comment by michaelfahmy** [comment]
This is still causing errors since zsh treats unquoted square brackets as glob patterns and errors out if no match is found.
