### ISSUE TITLE
Rubocop?

### ISSUE THREAD

**Issue by igor-alexandrov** [mrsked/mrsk#336]
How do you feel about adding Rubocop to the project?

**Comment by northeastprince** [comment]
Maybe standardrb instead? It's has more reasonable defaults imo and isn't as strict.

**Comment by igor-alexandrov** [comment]
Yes, standardrb seems like a good choice, but I still want to hear an opinion of somebody from MRSK team.

**Comment by dhh** [comment]
I don't think this project is big enough to warrant it at this stage.
