### ISSUE TITLE
`docker: command not found` error on host server

### ISSUE THREAD

**Issue by jeromedalbert** [mrsked/mrsk#338]
I was watching the [Introducing MRSK](https://www.youtube.com/watch?v=LL1cV2FXZ5I) Youtube screencast, and one of the steps early on is to run `mrsk deploy`. But I was getting the following error:

```
$ mrsk deploy
Acquiring the deploy lock...
Log into image registry...
  INFO [347dbde0] Running docker login -u [REDACTED] -p [REDACTED] as jerome@localhost
  INFO [347dbde0] Finished in 1.225 seconds with exit status 0 (successful).
  INFO [63af6e8d] Running docker login -u [REDACTED] -p [REDACTED] on [REDACTED]
Releasing the deploy lock...
  Finished all in 2.5 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host [REDACTED]: docker exit status: 127
docker stdout: Nothing written
docker stderr: bash: line 1: docker: command not found
```

It turned out that the video is out of sync with the current way of doing things. I should have followed the README instead, which mentions that you need to run the following command to install Docker on the server:

```
mrsk setup
```

This fixed the issue. Hopefully this writeup helps anyone who might have blindly followed the video like me.

**Comment by jeromedalbert** [comment]
Related issue: https://github.com/mrsked/mrsk/issues/301

**Comment by Danyaga** [comment]
Hello. I have to this issue even though I'm running `kamal setup`.

Basically, I added the second server and it seems that it isn't detecting that docker is installer in the first server, but not in the second.
