### ISSUE TITLE
Issue with branch or tag names containing dates

### ISSUE THREAD

**Issue by kiyo-e** [mrsked/mrsk#350]
Hello, I'm writing to report an issue we're experiencing with branch or tag names.

We have been using branch and docker image tag names that incorporate dates, for example "20230622-app". In such cases, only the "app" part is recognized as the version number and other commands such as "stop" do not work properly.

I would appreciate any help or guidance on how to fix this issue. Thank you for your assistance.

**Comment by djmb** [comment]
I think this and https://github.com/mrsked/mrsk/issues/402 and duplicates. Closing this one as the other has a bit more detail.
