### ISSUE TITLE
Uncommitted revision

### ISSUE THREAD

**Issue by dmitrytrager** [mrsked/mrsk#397]
Standard workflow (init, setup, deploy) delivers images with revision like <hash>_uncommitted_<hash> to server.
While "latest" version is expected to boot.

MRSK version 0.14

**Comment by dmitrytrager** [comment]
I have my .env file added to git ignore, so [this](https://github.com/mrsked/mrsk/discussions/378) won't fix the problem

**Comment by dhh** [comment]
Not sure what the standard workflow you're using is, but "uncommitted" will be added if "git status" isn't clean. That's by design.
