### ISSUE TITLE
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by jasonfb** [mrsked/mrsk#405]
I have confirmed that Docker in installed on the instance manually (https://github.com/mrsked/mrsk/issues/404) 

Now I'm getting 

```
% mrsk deploy
Acquiring the deploy lock...
Log into image registry...
  INFO [e77ce83d] Running docker login -u [REDACTED] -p [REDACTED] as jason@localhost
  INFO [e77ce83d] Finished in 2.102 seconds with exit status 0 (successful).
  INFO [a60bb274] Running docker login -u [REDACTED] -p [REDACTED] on 54.146.89.113
Releasing the deploy lock...
  Finished all in 4.1 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 54.146.89.113: docker exit status: 1
docker stdout: Nothing written
docker stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied
```

my `config/deploy.yml` file is

```
service: my-app

image: user/my-app

servers:
  - 54.146.89.113

registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: jasonheliosdevshop

  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

# Use a different ssh user than root
ssh:
  user: ubuntu


```

**Comment by jasonfb** [comment]
isn't --password being called from with in MRSK?

this SO post suggest to use `--password-stdin` and pass it a variable or something

https://stackoverflow.com/questions/51489359/docker-using-password-via-the-cli-is-insecure-use-password-stdin

**Comment by jasonfb** [comment]
https://discord.com/channels/1084848369073131531/1084848372667654248/1133867916534755360

- [ ] `sudo usermod -aG docker ${USER}`

**Comment by Michoels** [comment]
@jasonfb's solution worked for me.

Turns out it's also in the [official Docker docs](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user).

**Comment by indigotechtutorials** [comment]
This does work but shouldn't it be built into Kamal? if we are already doing all of that configuration on the server than running this simple command would be helpful. I just put up my own issue with the same thing here #1106
