### ISSUE TITLE
Docker Swarm

### ISSUE THREAD

**Issue by achempion** [mrsked/mrsk#42]
Very cool project. It reminds me a bit of [docker machine](https://github.com/docker/machine) for host configuration.

I can see that the current mrsk configuration is already growing with complex features like custom networking between hosts, accessories (running persistent services like a database), logging, service restarts / monitoring, secret management, etc.

Many of these challenges are already solved by Docker via Docker Swarm, with secrets management, network isolation, volumes, logging, rollout logic and much more. It has also solved many common cases and there is online help for many problems.

At the same time, I see that mrsk can be used to streamline swarm configuration and node setup, provide tooling in areas that are lacking, and let docker handle all other issues.

My questions is how mrsk is different from docker swarm as many of the challenges are already solved natively by docker ecosystem.

**Comment by dhh** [comment]
Yeah, would be nice to do a full comparison between the two. But I reviewed swarm in-depth before going down this path, and decided that wasn't going to be the route we went.

(There's no custom networking between hosts, btw. It's all running on the hosts.)

But hey, if you Swarm works well for you, then rock on.
