### ISSUE TITLE
Nope.   No k8s at fly.io.

### ISSUE THREAD

**Issue by rubys** [mrsked/mrsk#43]
> if you want to run on someone else's platform, like Render or Fly

You might want to change this to something like AWS or Google Cloud.

Fly definitely doesn't do Kubernetes.  And as far as I know, neither does Render, but I'm not an authority there.

Fly's model is fairly close to MRSK's.  Instead of `msrk init`, the command is `fly launch`.  Instead of `msrk deploy`, the command is `fly deploy`.   Instead of a. `config/deploy.yml`, we have a `fly.toml` file.  Instead of ip addresses, developers specify what regions they want to deploy to and how many servers they want there (including how much RAM).  We take care of assigning IP addresses and TLS certificates (via certbot).

Ignoring those differences, the model is that the developer works on their Rails app and maintains a Dockerfile, and when they are ready to ship, they run a deploy command.

In fact, there is no reason that a Rails application couldn't have both a `config/deploy.yml` and a `fly.toml` file, and deploy the same application using the same Dockerfile wherever they want.

**Comment by dhh** [comment]
Will reword. Totally agree that MRSK and Fly can coexist. You can start on Fly, then move to MRSK, or vice versa, with little/any app changes. 

Citation for Render on K8S: https://thenewstack.io/render-cloud-deployment-with-less-engineering/
