### ISSUE TITLE
postdeploy scripts

### ISSUE THREAD

**Issue by javierav** [mrsked/mrsk#48]
In some cases it is useful to run a script when the deployment is finished, for example for use [Airbrake Deploy Tracking](https://docs.airbrake.io/docs/features/deploy-tracking/) or notify by Slack.

**Comment by dhh** [comment]
Yes, intend to implement callbacks 👍

**Comment by azolf** [comment]
> 

Can I go with a PR for this?

**Comment by azolf** [comment]
> Yes, intend to implement callbacks 👍


Can I go with a PR for this?

**Comment by dhh** [comment]
Solved via https://github.com/mrsked/mrsk/pull/51.
