### ISSUE TITLE
Possible asset issue during deploy

### ISSUE THREAD

**Issue by edwinv** [mrsked/mrsk#60]
Great to see a new approach for deploying Rails apps 👏🏼

I haven’t tested mrsk out, but based on the documentation I expect there is an issue with the assets during deploys. Capistrano has this solved. We run our own deployment tooling and needed to solve this issue ourselves a few years ago.

The issue starts occurring once you have more than a couple of instances you are deploying to. The first instance can run a newer version than other servers. This new version wants to load new versions of the assets. Because they are timestamped/versioned, these assets are only available on the fresh instances. With more instances to deploy, the chance of hitting an old version increases. This means the assets 404 and no styling is present. In the end we reached a scale that we almost always had this issue with our deploys.

Capistrano solves this by sharing the assets between deploys. So older assets are still available. We have solved this by serving our assets from an s3 bucket with a CDN in front of it. By uploading the assets to the bucket before any instances are updated, you assure that all new versions can request the correct assets. 

Like I said, I haven’t tested mrsk so maybe there is a hidden solution to this issue and this can’t occur. But from my understanding of the deployment process, there is a risk of missing assets. Might be interesting to work this out before the issue starts happing at scale.

**Comment by SergeyBurtsev** [comment]
If each instance has it's own version of precompiled assets within it's container, there should be no problem, no?

**Comment by peterberkenbosch** [comment]
I think each container serves the assets from its own precompiled version, some can be outdated. Not sure how this would work when using a single CDN though without keeping some older refs around.

**Comment by edwinv** [comment]
> If each instance has it's own version of precompiled assets within it's container, there should be no problem, no?

Then you make the assumption that a request for a (new) asset lands on the same server. When using a load balancer you should never assume that is the case. 

> I think each container serves the assets from its own precompiled version, some can be outdated. Not sure how this would work when using a single CDN though without keeping some older refs around.

That’s why we use an s3 bucket with all versions. We remove the older versions on each deploy.

**Comment by dhh** [comment]
I'd solve that by letting your CDN be the cache of the old assets. Not going to introduce the complication of sharing assets between containers into MRSK. Assets are set to live for a year with no need to check the origin. So assets from old versions will continue to live in the CDN.

**Comment by dhh** [comment]
Actually, I see what you mean. That you serve HTML from a new version of the app, which then triggers a request for a new asset, which hits the CDN, the CDN then hits the app, which then potentially hits an old version that still hasn't been restarted. I think that window is pretty small with these deploys, but if we start doing rolling deploys, it could increase.

One way of dealing with it is using an asset host, then ensuring the asset host points to the first container instance that will be restarted first. But need to document that.

**Comment by Verdoso** [comment]
At scale, having an asset host that is restarted first would move the issue from the new version of the app to the old versions of the app. A user hits an old host that has not been restarted, gets an asset from the new app and things might break (old html with new styles, new Javascript referencing non existing fields).
Hence @edwinv solution of having them both available while the deploy is going on, and assuming you have implemented the proper naming/versioning so each version requests their own assets.

I don't see a general solution that mrsk can provide, but at allowing users to add their "custom things" at the proper moments might be enough, so maybe adding some kind of pre-/post-deployment hooks to add custom code to prepar/clean up assets?  If generalised, these hooks might even be used for other interesting things.

**Comment by dhh** [comment]
I don't think there's an issue in the other direction when you use a CDN that'll cache all old assets, and you ensure that the CDN uses the first-to-restart app as the origin for new assets. 

But yeah, would be happy to see general callbacks explored. The audit broadcast callback is one such specialized example.

**Comment by AxelTheGerman** [comment]
> when you use a CDN

and 

> when using a single CDN though without keeping some older refs around

I personally agree that the CDN should keep old assets around at least long enough for a deploy - if someone has humongous assets that are too expensive too keep they might need a special strategy there to purge as soon as it's safe.

I first thought assuming that folks use a CDN at all might be wrong, but when we're talking about a large deployment like this (not single containers where there is no issue) then I think documenting this somewhere might be good enough?

**Comment by dhh** [comment]
Yes, that's my view. This is a problem better handled at the CDN. This is how we keep MRSK small and light. Realizing that it's NOT a full-stack deployment framework, if you will. We're not trying to solve all possible deployment scenarios in this box. That's the pursuit for the likes of k8s or others. MRSK will stay lean by leaning on other modern, solutions that work with it.

So going to close this. Feel free to open a PR with documentation on this 👍

**Comment by shakalandy** [comment]
I think there is a misunderstanding of how CDNs work.
Just because you configure proper cache headers doesn't mean that CDNs will keep them for the time configured.
The time is not guaranteed, as unpopular assets will be evicted from cache and will require a repopulation from origin.

One would need a push-CDN for the described use-case, where you pay for cache storage size and get that space guaranteed - CDN will then take care about population of the assets - e.g. BunnyCDN offers that with ["perma-cache"](https://bunny.net/cdn/perma-cache/).

An easier solution would be to provide an "asset" volume which has a mechanism in place to keep several versioned old assets.

I think @dhh used Cloudflare in the example on YouTube, which is a Pull CDN which will not behave the same way as e.g. Cloudfront/S3.

**Comment by claasz** [comment]
Regardless whether your CDN supports a perma cache or not (or maybe you don't use a CDN at all), you could always put your app behind a standard HTTP caching server like Varnish, nginx, Apache+mod_cache.
