### ISSUE TITLE
schema.json for `deploy.yml` for auto completion

### ISSUE THREAD

**Issue by imWildCat** [mrsked/mrsk#63]
Hello!

Do we open to this idea to define a JSON schema (<https://json-schema.org>) for `deploy.yml`?

With this schema, we can write `deploy.yml` faster.

Related tutorial: https://dev.to/brpaz/how-to-create-your-own-auto-completion-for-json-and-yaml-files-on-vs-code-with-the-help-of-json-schema-k1i

**Comment by dhh** [comment]
Very open. See https://github.com/mrsked/mrsk/pull/37.

**Comment by dhh** [comment]
Yeah, I'll close. But do help out getting the other PR to the finish line, if you like.

**Comment by kjellberg** [comment]
It's pretty much ready and the validation is working, but we need to add all available configuration options and combinations. I'm not sure if they're considered "stable" yet? @dhh, the configs/fixtures at `test/fixtures/*.yml`, do they cover all possible configurations? 

I can give you write access to my patch if you'd like to help building the schema, @imWildCat. Here's the current version: https://github.com/kjellberg/mrsk/blob/dfa8ac899782678b808ea50d2e7e91256360db58/lib/mrsk/configuration/schema.yaml

**Comment by dhh** [comment]
I think things are stable enough 'ish that we can complete the schema in its current form. But yeah, we'll probably have a few more changes on the path to v1.0. I'm pretty sure we've exercised all the options possible in the test cases. If not, we surely should 😄

**Comment by imWildCat** [comment]
to celebrate Rails World 2024 and the RC of Kamal 2, I'm creating a community driven repo for the JSON Schema for v2!

https://github.com/RockieStar-Inc/kamal-json-schema
