### ISSUE TITLE
Non http service deployment

### ISSUE THREAD

**Issue by vadimi** [mrsked/mrsk#70]
I'm trying to deploy a non-rails service job in it's own container that doesn't use http. It looks like web role is always required and the deploy command is still trying to run traefik, health checks, getting error `ERROR (NoMethodError): undefined method 'hosts' for nil:NilClass` when not specifying web role.

What's the right process to deploy non http services?

**Comment by vadimi** [comment]
understood, thanks, just trying to deploy a go app that listens on messages from a queue, so traefik is not really needed for that.

**Comment by dhh** [comment]
Gotcha. I don't think MRSK is likely to be a good fit for that. Everything is directed towards running it with web apps.

**Comment by AdrianPop** [comment]
@vadimi here's a workaround I did and it works

I needed redis to be deployed without traefik, but as a separate app (custom usecase)
I've created a new docker image from the original redis with the below config

use original redis image, add python3 and multirun and serve an empty folder as healthcheck

```
FROM redis:7-alpine

RUN apk add --update python3 multirun curl
RUN mkdir /healthz

CMD multirun "redis-server" "python3 -m http.server -d /healthz 8000"
```

**Comment by Ehco1996** [comment]
> Gotcha. I don't think MRSK is likely to be a good fit for that. Everything is directed towards running it with web apps.

@dhh 

I understand that MRSK is designed primarily for web apps, but it's worth noting that many web applications also require asynchronous background jobs. These jobs are crucial for tasks like processing messages from a queue, sending emails, or performing other non-HTTP related tasks. e.g(celery for python and Sidekiq for rails)

Given that MRSK/Kamal aims to replace Kubernetes for many use cases, it seems logical to consider supporting non-HTTP services as well. What are your thoughts on expanding Kamal's capabilities to support such background job scenarios?

**Comment by dhh** [comment]
Kamal already supports that. But it's as part of a web application. The default Rails deploy.yml has an example showing how to run the application with background jobs. But it's off the same code base.

Anyway, no plan to pursue a web-less Kamal path. But feel free to fork and look at it!
