### ISSUE TITLE
"remote user name not available" with SSH connection

### ISSUE THREAD

**Issue by northeastprince** [mrsked/mrsk#81]
I'm getting this error whenever MRSK tries to establish an SSH connection to a server through [Teleport](https://goteleport.com), even though it works when I run `ssh root@******`.

![image-2~2.png](https://user-images.githubusercontent.com/55164724/222920654-650fccaa-935f-4c8f-8b35-ca70a885c728.png)

**Comment by jeremy** [comment]
Sounds like you'll need some Teleport config to map the user you're connecting as to the Teleport role. Out of scope here.
