### ISSUE TITLE
"mrsk config" exposes env secrets

### ISSUE THREAD

**Issue by kjellberg** [mrsked/mrsk#96]
There will be cases when a user is asked to copy the output of `mrsk config` for debugging. Currently it's a bad idea since all secrets are exposed in `env_args`, which also makes the following statement in README false:

`Marking an ENV as secret currently only redacts its value in the output for MRSK.`

**Comment by dhh** [comment]
Happy to see redact or similar applies to mrsk config, but the keys should be listed there.

**Comment by dhh** [comment]
Yes, all env inputs are meant to be listed. But we can add redacting.
